.PHONY: all clean deps run test coverage build docker docker-run

all: clean test build

# clean the tmp and result file generated by the test command
clean:
		rm -rf target; \
		rm -f coverage.*

deps: clean
		go get -d -v ./...

run: deps
		go run *.go

test: deps
		go clean -testcache ./...
		go test -count=1 ./...

coverage: test
		go test -coverprofile=coverage.out ./...; \
		go tool cover -html=coverage.out -o coverage.html

build:	deps
		CGO_ENABLED=0 GOOS=linux \
       		go build \
       		-a -installsuffix cgo \
       		-tags=jsoniter -o target/app .

docker: build
		docker build -t app .

docker-run: docker
		docker run -it -p 8080:8080 app